version: '3'

services:
  server:
    image: node:10.14.2-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/linkapi/mongo
  webhook:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040:4040
    environment:
      TARGET_HOST: server
      TARGET_PORT: 8080
      NGROK_REGION: us
      NGROK_TOKEN: ${NGROK_TOKEN}

volumes:
  mongodata:
